# Methane Kit CI configuration
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - Build/Windows/Build.bat
    - Build/Unix/Build.sh
    - CMakeSettings.json
    - Folder.DotSettings
    - README.md
    - LICENSE

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - CMakeSettings.json

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: recursive

variables:

  product.Version.Major: 0
  product.Version.Minor: 6
  product.Version.Full: '$(product.Version.Major).$(product.Version.Minor).$(Build.BuildNumber)'

  sonar.CloudName: 'Evgeny Gorodetsky Sonar Cloud'
  sonar.Organization: 'egorodet-github'
  sonar.Sources: 'Apps,Modules'
  sonar.Tests: 'Tests'
  sonar.CacheDir: '$(Pipeline.Workspace)/SonarCache'
  sonar.ScannerVersion: '4.4.0.2170'

  buildReleaseCmakeFlags: '-DMETHANE_VERSION_MAJOR=$(product.Version.Major)
    -DMETHANE_VERSION_MINOR=$(product.Version.Minor)
    -DMETHANE_VERSION_BUILD=$(Build.BuildNumber)
    -DMETHANE_SHADERS_CODEVIEW_ENABLED:BOOL=ON
    -DMETHANE_RUN_TESTS_DURING_BUILD:BOOL=OFF
    -DMETHANE_COMMAND_DEBUG_GROUPS_ENABLED:BOOL=ON
    -DMETHANE_LOGGING_ENABLED:BOOL=OFF
    -DMETHANE_OPEN_IMAGE_IO_ENABLED:BOOL=OFF
    -DMETHANE_SCOPE_TIMERS_ENABLED:BOOL=OFF
    -DMETHANE_ITT_INSTRUMENTATION_ENABLED:BOOL=ON
    -DMETHANE_ITT_METADATA_ENABLED:BOOL=OFF
    -DMETHANE_GPU_INSTRUMENTATION_ENABLED:BOOL=OFF
    -DMETHANE_TRACY_PROFILING_ENABLED:BOOL=OFF
    -DMETHANE_TRACY_PROFILING_ON_DEMAND:BOOL=OFF'

  buildProfilingCmakeFlags: '-DMETHANE_VERSION_BUILD=$(Build.BuildNumber)
    -DMETHANE_SHADERS_CODEVIEW_ENABLED:BOOL=ON
    -DMETHANE_RUN_TESTS_DURING_BUILD:BOOL=OFF
    -DMETHANE_COMMAND_DEBUG_GROUPS_ENABLED:BOOL=ON
    -DMETHANE_LOGGING_ENABLED:BOOL=OFF
    -DMETHANE_OPEN_IMAGE_IO_ENABLED:BOOL=OFF
    -DMETHANE_SCOPE_TIMERS_ENABLED:BOOL=ON
    -DMETHANE_ITT_INSTRUMENTATION_ENABLED:BOOL=ON
    -DMETHANE_ITT_METADATA_ENABLED:BOOL=ON
    -DMETHANE_GPU_INSTRUMENTATION_ENABLED:BOOL=ON
    -DMETHANE_TRACY_PROFILING_ENABLED:BOOL=ON
    -DMETHANE_TRACY_PROFILING_ON_DEMAND:BOOL=ON'

  buildScanCmakeFlags: '-DMETHANE_VERSION_BUILD=$(Build.BuildNumber)
    -DMETHANE_CODE_COVERAGE_ENABLED:BOOL=ON
    -DMETHANE_RUN_TESTS_DURING_BUILD:BOOL=OFF
    -DMETHANE_UNITY_BUILD_ENABLED:BOOL=OFF'

jobs:

- job: Win64_DX_Release

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'Release'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: 'Win64-DX-Release'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml

- job: Win64_DX_Profiling

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'RelWithDebInfo'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildProfilingCmakeFlags)
    buildName: 'Win64-DX-Profiling'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml
    parameters:
      runTests: false

- job: Win32_DX_Release

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win32'
    configuration: 'Release'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: 'Win32-DX-Release'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml
    parameters:
      runTests: false

- job: Win32_DX_Profiling

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win32'
    configuration: 'RelWithDebInfo'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildProfilingCmakeFlags)
    buildName: 'Win32-DX-Profiling'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml
    parameters:
      runTests: false

- job: Win64_VK_Release

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'Release'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_GFX_VULKAN_ENABLED:BOOL=ON -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildReleaseCmakeFlags)
    buildName: 'Win64-VK-Release'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
    - template: Build/Windows/AzureBuild.yml
      parameters:
        runTests: false

- job: Win64_VK_Profiling

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'RelWithDebInfo'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_GFX_VULKAN_ENABLED:BOOL=ON -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildProfilingCmakeFlags)
    buildName: 'Win64-VK-Profiling'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
    - template: Build/Windows/AzureBuild.yml
      parameters:
        runTests: false

- job: Win32_VK_Release

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win32'
    configuration: 'Release'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_GFX_VULKAN_ENABLED:BOOL=ON -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildReleaseCmakeFlags)
    buildName: 'Win32-VK-Release'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
    - template: Build/Windows/AzureBuild.yml
      parameters:
        runTests: false

- job: Win32_VK_Profiling

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win32'
    configuration: 'RelWithDebInfo'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_GFX_VULKAN_ENABLED:BOOL=ON -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildProfilingCmakeFlags)
    buildName: 'Win32-VK-Profiling'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
    - template: Build/Windows/AzureBuild.yml
      parameters:
        runTests: false

- job: Win64_DX_Sonar_Scan
  continueOnError: true

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'Debug'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildScanCmakeFlags)
    buildName: 'Win64-DX-SonarScan'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'
    vcVarsBatFile: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    sonar.ProjectKey: 'egorodet_MethaneKit_Windows'
    sonar.BuildWrapperUrl: 'https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip'
    sonar.BuildWrapperExe: build-wrapper-win-x86\build-wrapper-win-x86-64.exe
    sonar.BuildCommand: MSBuild.exe INSTALL.vcxproj /p:Configuration=$(configuration) /p:Platform=$(platform) /t:Rebuild
    sonar.Verbose: false

  steps:
    - template: Build/Windows/AzureSonarScan.yml

- job: MacOS_MTL_Release

  pool:
    vmImage: 'macOS-10.15'

  variables:
    platform: 'MacOS'
    configuration: 'Release'
    generatorName: 'Xcode'
    cmakeFlags: -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" $(buildReleaseCmakeFlags)
    buildName: 'MacOS-MTL-Release'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'

  steps:
  - template: Build/Unix/AzureBuild.yml

- job: MacOS_MTL_Profiling

  pool:
    vmImage: 'macOS-10.15'

  variables:
    platform: 'MacOS'
    configuration: 'RelWithDebInfo'
    generatorName: 'Xcode'
    cmakeFlags: -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DMETHANE_TESTS_BUILD_ENABLED:BOOL=OFF $(buildProfilingCmakeFlags)
    buildName: 'MacOS-MTL-Profiling'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'

  steps:
  - template: Build/Unix/AzureBuild.yml
    parameters:
      runTests: false

- job: MacOS_MTL_Sonar_Scan
  continueOnError: true

  pool:
    vmImage: 'macOS-10.15'

  variables:
    platform: 'MacOS'
    configuration: 'Debug'
    generatorName: 'Xcode'
    cmakeFlags: -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" $(buildScanCmakeFlags)
    buildName: 'MacOS-MTL-SonarScan'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'
    coverageReports: '$(installDir)/Tests/Coverage/*.lcov'
    sonar.ProjectKey: 'egorodet_MethaneKit_MacOS'
    sonar.BuildWrapperUrl: 'https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip'
    sonar.BuildWrapperExe: build-wrapper-macosx-x86/build-wrapper-macosx-x86
    sonar.BuildCommand: xcodebuild -project MethaneKit.xcodeproj -target install -configuration $(configuration) build
    sonar.Verbose: false

  steps:
    - template: Build/Unix/AzureSonarScan.yml
      parameters:
        extraScanSteps:
          - bash: |
              result_ext='.xml'
              prof_data_ext='.profdata'
              prof_raw_ext='.profraw'
              lcov_ext='.lcov'
              echo Running unit-tests and Converting LLVM code coverage data to lcov text format in directory $PWD
              mkdir Results
              mkdir Coverage
              for test_exe in *Test
              do
                ./$test_exe -r sonarqube -o "Results/$test_exe$result_ext"
                echo  - $test_exe - completed with $? exit status
                if [ ! -f default.profraw ]; then
                  continue
                fi
                mv default.profraw "$test_exe$prof_raw_ext"
                xcrun llvm-profdata merge -o "$test_exe$prof_data_ext" "$test_exe$prof_raw_ext"
                xcrun llvm-cov export -format lcov -instr-profile="$test_exe$prof_data_ext" -arch=x86_64 ./$test_exe > "./Coverage/$test_exe$lcov_ext"
                echo    - Converted code coverage from "$test_exe$prof_raw_ext" to lcov text format "./Coverage/$test_exe$lcov_ext", $? exit status
              done
              echo List of generated coverage files in directory $PWD/Coverage
              ls -la ./Coverage
            workingDirectory: '$(installDir)/Tests'
            displayName: 'Collect code coverage from all unit-tests in install directory on MacOS'

- job: Ubuntu_VK_Release

  pool:
    vmImage: 'ubuntu-20.04'

  variables:
    platform: 'Ubuntu'
    configuration: 'Release'
    generatorName: '"Unix Makefiles"'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: 'Ubuntu-VK-Release'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'

  steps:
  - template: Build/Unix/AzureBuild.yml
    parameters:
      extraInitSteps:
        - bash: |
            sudo apt-get update
            sudo apt-get install libx11-xcb-dev
          displayName: 'Install prerequisite packages on Linux'

- job: Ubuntu_VK_Sonar_Scan
  continueOnError: true

  pool:
    vmImage: 'ubuntu-20.04'

  variables:
    platform: 'Ubuntu'
    configuration: 'Debug'
    generatorName: '"Unix Makefiles"'
    cmakeFlags: $(buildScanCmakeFlags)
    buildName: 'Ubuntu-VK-SonarScan'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'
    coverageReports: '$(buildDir)/MethaneTestCoverage.info'
    sonar.ProjectKey: 'egorodet_MethaneKit_Linux'
    sonar.BuildWrapperUrl: 'https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip'
    sonar.BuildWrapperExe: build-wrapper-linux-x86/build-wrapper-linux-x86-64
    sonar.BuildCommand: make install
    sonar.Verbose: false

  steps:
    - template: Build/Unix/AzureSonarScan.yml
      parameters:
        extraInitSteps:
          - bash: |
              sudo apt-get update
              sudo apt-get install lcov libx11-xcb-dev
            displayName: 'Install prerequisite packages on Linux'
        extraScanSteps:
          - bash: |
              result_ext='.xml'
              echo Running unit-tests in directory $PWD
              mkdir Results
              for test_exe in *Test
              do
                ./$test_exe -r sonarqube -o "Results/$test_exe$result_ext"
                echo  - $test_exe - completed with $? exit status
              done
            workingDirectory: '$(installDir)/Tests'
            displayName: 'Run all unit-tests from install directory'
          - bash: |
              make MethaneTestCoverage
            workingDirectory: '$(buildDir)'
            displayName: 'Collect tests code coverage using ctest and gcov/lcov on Linux'