# Methane Kit CI configuration
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - Build/Windows/Build.bat
    - Build/Posix/Build.sh
    - CMakeSettings.json
    - Folder.DotSettings
    - README.md
    - LICENSE

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - CMakeSettings.json

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: recursive

variables:

  product.Version.Major: 0
  product.Version.Minor: 5
  product.Version.Full: '$(product.Version.Major).$(product.Version.Minor).$(Build.BuildNumber)'

  sonar.CloudName: 'Evgeny Gorodetsky Sonar Cloud'
  sonar.Organization: 'egorodet-github'
  sonar.Sources: 'Apps,Modules'
  sonar.Tests: 'Modules/**/Test/'
  sonar.CacheDir: '$(Pipeline.Workspace)/SonarCache'

  buildReleaseCmakeFlags: '-DMETHANE_VERSION_MAJOR=$(product.Version.Major)
    -DMETHANE_VERSION_MINOR=$(product.Version.Minor)
    -DMETHANE_VERSION_BUILD=$(Build.BuildNumber)
    -DMETHANE_SHADERS_CODEVIEW_ENABLED:BOOL=ON
    -DMETHANE_RUN_TESTS_DURING_BUILD:BOOL=OFF
    -DMETHANE_COMMAND_DEBUG_GROUPS_ENABLED:BOOL=ON
    -DMETHANE_LOGGING_ENABLED:BOOL=OFF
    -DMETHANE_USE_OPEN_IMAGE_IO:BOOL=OFF
    -DMETHANE_SCOPE_TIMERS_ENABLED:BOOL=OFF
    -DMETHANE_ITT_INSTRUMENTATION_ENABLED:BOOL=ON
    -DMETHANE_ITT_METADATA_ENABLED:BOOL=OFF
    -DMETHANE_GPU_INSTRUMENTATION_ENABLED:BOOL=OFF
    -DMETHANE_TRACY_PROFILING_ENABLED:BOOL=OFF
    -DMETHANE_TRACY_PROFILING_ON_DEMAND:BOOL=OFF'

  buildProfilingCmakeFlags: '-DMETHANE_VERSION_BUILD=$(Build.BuildNumber)
    -DMETHANE_SHADERS_CODEVIEW_ENABLED:BOOL=ON
    -DMETHANE_RUN_TESTS_DURING_BUILD:BOOL=OFF
    -DMETHANE_COMMAND_DEBUG_GROUPS_ENABLED:BOOL=ON
    -DMETHANE_LOGGING_ENABLED:BOOL=OFF
    -DMETHANE_USE_OPEN_IMAGE_IO:BOOL=OFF
    -DMETHANE_SCOPE_TIMERS_ENABLED:BOOL=ON
    -DMETHANE_ITT_INSTRUMENTATION_ENABLED:BOOL=ON
    -DMETHANE_ITT_METADATA_ENABLED:BOOL=ON
    -DMETHANE_GPU_INSTRUMENTATION_ENABLED:BOOL=ON
    -DMETHANE_TRACY_PROFILING_ENABLED:BOOL=ON
    -DMETHANE_TRACY_PROFILING_ON_DEMAND:BOOL=ON'

jobs:

- job: Windows_x64

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'Release'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: 'Win64-$(configuration)'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml

- job: Windows_x64_Profiling

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win64'
    configuration: 'RelWithDebInfo'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildProfilingCmakeFlags)
    buildName: 'Win64-$(configuration)-Profiling'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml

- job: Windows_x86

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win32'
    configuration: 'Release'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: '$(platform)-$(configuration)'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml

- job: Windows_x86_Profiling

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'Win32'
    configuration: 'RelWithDebInfo'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: $(buildProfilingCmakeFlags)
    buildName: '$(platform)-$(configuration)-Profiling'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'

  steps:
  - template: Build/Windows/AzureBuild.yml

- job: Windows_Sonar_Scan

  pool:
    vmImage: 'windows-2019'

  variables:
    platform: 'x64'
    configuration: 'Debug'
    generatorName: '"Visual Studio 16 2019"'
    cmakeFlags: -DMETHANE_UNITY_BUILD_ENABLED:BOOL=OFF $(buildReleaseCmakeFlags)
    buildName: '$(platform)-$(configuration)-SonarScan'
    buildDir: 'Build\Output\$(buildName)\Build'
    installDir: 'Build\Output\$(buildName)\Install'
    buildInstallDir: '..\Install'
    rootDir: '..\..\..\..'
    vcVarsBatFile: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    sonar.ProjectKey: 'egorodet_MethaneKit_Windows'
    sonar.BuildWrapperUrl: 'https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip'
    sonar.BuildWrapperExe: build-wrapper-win-x86\build-wrapper-win-x86-64.exe
    sonar.BuildCommand: MSBuild.exe INSTALL.vcxproj /p:Configuration=$(configuration) /p:Platform=$(platform) /t:Rebuild

  steps:
    - template: Build/Windows/AzureSonarScan.yml

- job: MacOS

  pool:
    vmImage: 'macOS-10.14'

  variables:
    platform: 'MacOS'
    configuration: 'Release'
    generatorName: 'Xcode'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: '$(platform)-$(configuration)'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'

  steps:
  - template: Build/Posix/AzureBuild.yml

- job: MacOS_Profiling

  pool:
    vmImage: 'macOS-10.14'

  variables:
    platform: 'MacOS'
    configuration: 'RelWithDebInfo'
    generatorName: 'Xcode'
    cmakeFlags: $(buildProfilingCmakeFlags)
    buildName: '$(platform)-$(configuration)-Profiling'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'

  steps:
  - template: Build/Posix/AzureBuild.yml

- job: MacOS_Sonar_Scan

  pool:
    vmImage: 'macOS-10.14'

  variables:
    platform: 'MacOS'
    configuration: 'Debug'
    generatorName: 'Xcode'
    cmakeFlags: -DMETHANE_UNITY_BUILD_ENABLED:BOOL=OFF $(buildReleaseCmakeFlags)
    buildName: '$(platform)-$(configuration)-SonarScan'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'
    sonar.ProjectKey: 'egorodet_MethaneKit_MacOS'
    sonar.BuildWrapperUrl: 'https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip'
    sonar.BuildWrapperExe: build-wrapper-macosx-x86/build-wrapper-macosx-x86
    sonar.BuildCommand: xcodebuild -project MethaneKit.xcodeproj -configuration $(configuration) clean build

  steps:
    - template: Build/Posix/AzureSonarScan.yml

- job: Ubuntu

  pool:
    vmImage: 'ubuntu-18.04'

  variables:
    platform: 'Ubuntu'
    configuration: 'Release'
    generatorName: '"Unix Makefiles"'
    cmakeFlags: $(buildReleaseCmakeFlags)
    buildName: '$(platform)-$(configuration)'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'

  steps:
  - template: Build/Posix/AzureBuild.yml

- job: Ubuntu_Sonar_Scan

  pool:
    vmImage: 'ubuntu-18.04'

  variables:
    platform: 'Ubuntu'
    configuration: 'Debug'
    generatorName: '"Unix Makefiles"'
    cmakeFlags: -DMETHANE_UNITY_BUILD_ENABLED:BOOL=OFF $(buildReleaseCmakeFlags)
    buildName: '$(platform)-$(configuration)-SonarScan'
    buildDir: 'Build/Output/$(buildName)/Build'
    installDir: 'Build/Output/$(buildName)/Install'
    buildInstallDir: '../Install'
    rootDir: '../../../..'
    sonar.ProjectKey: 'egorodet_MethaneKit_Linux'
    sonar.BuildWrapperUrl: 'https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip'
    sonar.BuildWrapperExe: build-wrapper-linux-x86/build-wrapper-linux-x86-64
    sonar.BuildCommand: make clean all

  steps:
    - template: Build/Posix/AzureSonarScan.yml