# Cross-platform and multi-configuration build of the Methane Kit

name: 'CI Build'

on:
  push:
    branches: [ master, develop ]
    paths:
    - '.github/workflows/ci-build.yml'
    - 'Apps/**'
    - 'Modules/**'
    - 'Externals/**'
    - 'CMake/**'
    - 'CMakeLists.txt'
    - 'CMakePresets.json'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/ci-build.yml'
    - 'Apps/**'
    - 'Modules/**'
    - 'Externals/**'
    - 'CMake/**'
    - 'CMakeLists.txt'
    - 'CMakePresets.json'
  schedule:
    - cron: '20 23 * * 3'

env:
  product_ver_major: 0
  product_ver_minor: 7
  product_ver_patch: 0
  product_ver_build: ${{ github.run_number }}
  TRACY_NO_INVARIANT_CHECK: 1

jobs:
  build:
    name: ${{ matrix.name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            name: "Win64_DX_Release"
            config_preset: "VS2019-Win64-DX-Default"
            build_preset: "VS2019-Win64-DX-Release"
            named_logo: Windows
            run_tests: true

          - os: windows-2019
            name: "Win64_VK_Release"
            config_preset: "VS2019-Win64-VK-Default"
            build_preset: "VS2019-Win64-VK-Release"
            named_logo: Windows
            run_tests: true

          - os: windows-2019
            name: "Win64_DX_Profile"
            config_preset: "VS2019-Win64-DX-Profile"
            build_preset: "VS2019-Win64-DX-Profile"
            named_logo: Windows
            run_tests: false

          - os: windows-2019
            name: "Win64_VK_Profile"
            config_preset: "VS2019-Win64-VK-Profile"
            build_preset: "VS2019-Win64-VK-Profile"
            named_logo: Windows
            run_tests: false

          - os: windows-2019
            name: "Win32_DX_Release"
            config_preset: "VS2019-Win32-DX-Default"
            build_preset: "VS2019-Win32-DX-Release"
            named_logo: Windows
            run_tests: true

          - os: windows-2019
            name: "Win32_VK_Release"
            config_preset: "VS2019-Win32-VK-Default"
            build_preset: "VS2019-Win32-VK-Release"
            named_logo: Windows
            run_tests: true

          - os: windows-2019
            name: "Win32_DX_Profile"
            config_preset: "VS2019-Win32-DX-Profile"
            build_preset: "VS2019-Win32-DX-Profile"
            named_logo: Windows
            run_tests: false

          - os: windows-2019
            name: "Win32_VK_Profile"
            config_preset: "VS2019-Win32-VK-Profile"
            build_preset: "VS2019-Win32-VK-Profile"
            named_logo: Windows
            run_tests: false

          - os: ubuntu-latest
            name: "Ubuntu_VK_Release"
            config_preset: "Make-Lin-VK-Release"
            build_preset: "Make-Lin-VK-Release"
            named_logo: Linux
            run_tests: true

          - os: ubuntu-latest
            name: "Ubuntu_VK_Profile"
            config_preset: "Make-Lin-VK-Profile"
            build_preset: "Make-Lin-VK-Profile"
            named_logo: Linux
            run_tests: false

          - os: macos-latest
            name: "MacOS_MTL_Release"
            config_preset: "Xcode-Mac-MTL-Default"
            build_preset: "Xcode-Mac-MTL-Release"
            named_logo: Linux
            run_tests: true

          - os: macos-latest
            name: "MacOS_MTL_Profile"
            config_preset: "Xcode-Mac-MTL-Profile"
            build_preset: "Xcode-Mac-MTL-Profile"
            named_logo: Apple
            run_tests: false

          - os: macos-latest
            name: "iOS_Sim_MTL_Release"
            config_preset: "Xcode-iOS-Sim-MTL-Default"
            build_preset: "Xcode-iOS-Sim-MTL-Release"
            named_logo: Apple
            run_tests: false

          - os: macos-latest
            name: "tvOS_Sim_MTL_Release"
            config_preset: "Xcode-tvOS-Sim-MTL-Default"
            build_preset: "Xcode-tvOS-Sim-MTL-Release"
            named_logo: Apple
            run_tests: false

    runs-on: ${{ matrix.os }}

    steps:

    - name: Install Linux prerequisites
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install xcb libx11-dev libx11-xcb-dev libxcb-randr0-dev p7zip

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Testspace
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{ github.repository_owner }}

    - name: Initialize Externals Cache
      uses: actions/cache@v3
      with:
        path: Build/Output/ExternalsCache
        key: ExternalsCache-${{ matrix.config_preset }}-${{ hashFiles('Externals/*.cmake') }}

    - name: CMake Configure Preset ${{ matrix.config_preset }}
      run: cmake --preset ${{ matrix.config_preset }} -DMETHANE_VERSION_MAJOR=${{ env.product_ver_major }} -DMETHANE_VERSION_MINOR=${{ env.product_ver_minor }} -DMETHANE_VERSION_PATCH=${{ env.product_ver_patch }} -DMETHANE_VERSION_BUILD=${{ env.product_ver_build }}

    - name: CMake Build Preset ${{ matrix.build_preset }}
      run: cmake --build --preset ${{ matrix.build_preset }} --target install --parallel 4

    - name: Run Unit-Tests on Unix
      if: ${{ matrix.run_tests && matrix.os != 'windows-2019'}}
      working-directory: Build/Output/${{ matrix.config_preset }}/Install/Tests
      shell: bash
      run: |
        result_ext='_result.xml'
        echo Running all unit-tests in directory $PWD
        for test_exe in *Test
        do
          ./$test_exe -r junit -o "$test_exe$result_ext"
          echo  - $test_exe - completed with $? exit code
        done

    - name: Run Unit-Tests on Windows
      if: ${{ matrix.run_tests && matrix.os == 'windows-2019' }}
      working-directory: Build/Output/${{ matrix.config_preset }}/Install/Tests
      shell: cmd
      run: |
        setlocal enabledelayedexpansion
        echo Running unit-tests in directory "%cd%"
        for /r "." %%a in (*Test.exe) do (
          "%%~fa" -r junit -o "%%~fa_result.xml"
          echo  - %%~na - completed with !errorlevel! exit status
        )
        exit 0

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: ${{ matrix.run_tests && (success() || failure()) }}
      with:
        name: MethaneKit_${{ matrix.name }}_TestResults_${{ env.product_ver_major }}.${{ env.product_ver_minor }}.${{ env.product_ver_patch }}.${{ env.product_ver_build }}
        path: Build/Output/${{ matrix.config_preset }}/Install/Tests/*_result.xml

    - name: Publish test results to Testspace server
      if: ${{ matrix.run_tests && (success() || failure()) }}
      run: testspace "[ ${{ matrix.name }} ]Build/Output/${{ matrix.config_preset }}/Install/Tests/*_result.xml"

    - name: Archive Build Artifacts
      shell: bash
      working-directory: Build/Output/${{ matrix.config_preset }}/Install
      run: 7z a -t7z -mx=9 MethaneKit_${{ matrix.name }}.7z *

    - name: Upload Archived Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MethaneKit_${{ matrix.name }}_${{ env.product_ver_major }}.${{ env.product_ver_minor }}.${{ env.product_ver_patch }}.${{ env.product_ver_build }}
        path: Build/Output/${{ matrix.config_preset }}/Install/MethaneKit_${{ matrix.name }}.7z

    - name: Update Badge Parameters
      id: badge-params
      if: ${{ github.event_name == 'push' && always() }}
      shell: bash
      run: |
        case "${{ job.status }}" in
          "success")
            echo "::set-output name=message::passing"
            echo "::set-output name=color::green"
            ;;
          "failure")
            echo "::set-output name=message::failing"
            echo "::set-output name=color::red"
            ;;
          "cancelled")
            echo "::set-output name=message::cancelled"
            echo "::set-output name=color::lightgray"
            ;;
          *)
            echo "::set-output name=message::undefined"
            echo "::set-output name=color::purple"
            ;;
        esac

    - name: Update Badge JSON
      if: ${{ github.event_name == 'push' && always() }}
      uses: schneegans/dynamic-badges-action@v1.4.0 # https://github.com/marketplace/actions/dynamic-badges
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 96d788046ccd52b45b3354a99f8569c3
        filename: MethaneKit_${{ matrix.name }}_${{ github.ref_name }}.json
        namedLogo: ${{ matrix.named_logo }} # https://simpleicons.org
        label: ${{ matrix.name }}
        labelColor: gray
        message: ${{ steps.badge-params.outputs.message }}
        color: ${{ steps.badge-params.outputs.color }}
        isError: ${{ failure() }}
